-- Create News Table
create table public.news (
  id bigint generated by default as identity primary key,
  date text not null,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Diary Table
create table public.diary (
  id bigint generated by default as identity primary key,
  date text not null,
  title text not null,
  content text not null,
  progress integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Characters Table
create table public.characters (
  id text primary key,
  name text not null,
  role text not null,
  description text not null,
  image text not null,
  color text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Videos Table
create table public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.news enable row level security;
alter table public.diary enable row level security;
alter table public.characters enable row level security;
alter table public.videos enable row level security;

-- Create Policies (Public Read Access)
create policy "Public items are viewable by everyone." on public.news for select using (true);
create policy "Public items are viewable by everyone." on public.diary for select using (true);
create policy "Public items are viewable by everyone." on public.characters for select using (true);
create policy "Public items are viewable by everyone." on public.videos for select using (true);

-- Create Policies (Admin Write Access - dependent on auth, but for now we might use service key or authenticated users)
-- For simplicity in this phase, we'll allow authenticated users to insert/update/delete, assuming only admin logs in.
create policy "Authenticated users can insert." on public.news for insert to authenticated with check (true);
create policy "Authenticated users can update." on public.news for update to authenticated using (true);
create policy "Authenticated users can delete." on public.news for delete to authenticated using (true);

create policy "Authenticated users can insert." on public.diary for insert to authenticated with check (true);
create policy "Authenticated users can update." on public.diary for update to authenticated using (true);
create policy "Authenticated users can delete." on public.diary for delete to authenticated using (true);

create policy "Authenticated users can insert." on public.videos for insert to authenticated with check (true);
create policy "Authenticated users can update." on public.videos for update to authenticated using (true);
create policy "Authenticated users can delete." on public.videos for delete to authenticated using (true);

-- Characters might be static or editable, adding policies just in case
create policy "Authenticated users can insert." on public.characters for insert to authenticated with check (true);
create policy "Authenticated users can update." on public.characters for update to authenticated using (true);
create policy "Authenticated users can delete." on public.characters for delete to authenticated using (true);

-- Initial Data Migration
-- News
insert into public.news (date, title, content) values
('2026.01.04', 'ウェブサイトを開設しました', '秘封工倶楽部の公式サイトを公開しました。今後の活動はここでお知らせします。'),
('2025.12.30', 'C107 参加御礼', 'コミックマーケット107では当スペースにお越しいただきありがとうございました。');

-- Diary
insert into public.diary (date, title, content, progress) values
('2026.01.02', '次回作のシナリオプロット作成中', '秘封倶楽部が異界を探索するシークエンスの構成を練っています。今回は少しホラー要素を強めにしたい。', 15),
('2025.12.25', '年末の進捗報告', '背景美術のコンセプトアートが数枚完成しました。冬のコミケには間に合いませんでしたが、春にはティザーを出したいです。', 5);

-- Characters
insert into public.characters (id, name, role, description, image, color) values
('renko', '宇佐見 蓮子', '物理学者 / シナリオ構成', '星を見ただけで時間が分かり、月を見ただけで場所が分かる程度の能力を持つ。客観的・論理的な視点から「不思議」を解明しようとする。', '/images/renko.png', '#1a1a1a'),
('merry', 'マエリベリー・ハーン', 'オカルト専攻 / 境界観測', '結界の裂け目を見る程度の能力を持つ。主観的な体験を通して「不思議」を受け入れる。愛称はメリー。', '/images/merry.png', '#e0b0ff');

-- Videos
insert into public.videos (title, url) values
('あｓ', 'https://www.youtube.com/watch?v=FTbdMWSwjyI');

